var searchData=
[
  ['iconversationcontext_0',['IConversationContext',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IConversationContext.html',1,'WolfstagInteractive::ConvoCore']]],
  ['iconvocorecharacterdisplay_1',['IConvoCoreCharacterDisplay',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreCharacterDisplay.html',1,'WolfstagInteractive::ConvoCore']]],
  ['iconvocorefadein_2',['IConvoCoreFadeIn',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeIn.html',1,'WolfstagInteractive::ConvoCore']]],
  ['iconvocorefadeout_3',['IConvoCoreFadeOut',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeOut.html',1,'WolfstagInteractive::ConvoCore']]],
  ['iconvocorehistoryrenderer_4',['IConvoCoreHistoryRenderer',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreHistoryRenderer.html',1,'WolfstagInteractive::ConvoCore']]],
  ['iconvocorelanguagesettingsloader_5',['IConvoCoreLanguageSettingsLoader',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreLanguageSettingsLoader.html',1,'WolfstagInteractive::ConvoCore']]],
  ['iconvocorerepresentationinitializable_6',['IConvoCoreRepresentationInitializable',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRepresentationInitializable.html',1,'WolfstagInteractive::ConvoCore']]],
  ['iconvocorerunner_7',['IConvoCoreRunner',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRunner.html',1,'WolfstagInteractive::ConvoCore']]],
  ['iconvoinput_8',['IConvoInput',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoInput.html',1,'WolfstagInteractive::ConvoCore']]],
  ['idialoguehistoryoutput_9',['IDialogueHistoryOutput',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutput.html',1,'WolfstagInteractive::ConvoCore']]],
  ['idialoguehistoryoutputprefab_10',['IDialogueHistoryOutputPrefab',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutputPrefab.html',1,'WolfstagInteractive::ConvoCore']]],
  ['idialoguelineeditorcustomizable_11',['IDialogueLineEditorCustomizable',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueLineEditorCustomizable.html',1,'WolfstagInteractive::ConvoCore']]],
  ['ieditorpreviewablerepresentation_12',['IEditorPreviewableRepresentation',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IEditorPreviewableRepresentation.html',1,'WolfstagInteractive::ConvoCore']]],
  ['importfromyamlforkey_13',['ImportFromYamlForKey',['../classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlUtilities.html#af2026fa5cd1d453b42ed7a93f84fd84b',1,'WolfstagInteractive::ConvoCore::ConvoCoreYamlUtilities']]],
  ['initializedialoguedata_14',['InitializeDialogueData',['../classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreConversationData.html#a09612aa9355dacb5a44b70efec796302',1,'WolfstagInteractive::ConvoCore::ConvoCoreConversationData']]],
  ['initializerenderer_15',['InitializeRenderer',['../classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueHistoryUI.html#a3c5d5267be39536fa2509919d095b4ff',1,'WolfstagInteractive::ConvoCore::ConvoCoreDialogueHistoryUI']]],
  ['initializeui_16',['initializeui',['../classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSampleUI.html#a24435d7a1be4c6f8d3f07d710e90f1da',1,'WolfstagInteractive.ConvoCore.ConvoCoreSampleUI.InitializeUI()'],['../classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreUIFoundation.html#a06a54cd4a4baa430447c7972ea95220b',1,'WolfstagInteractive.ConvoCore.ConvoCoreUIFoundation.InitializeUI()'],['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IUIFoundation.html#a2e3c37bcbbea84f7b7d75c50e342066d',1,'WolfstagInteractive.ConvoCore.IUIFoundation.InitializeUI()']]],
  ['isvalid_17',['IsValid',['../classWolfstagInteractive_1_1ConvoCore_1_1GameObjectReference.html#a2d5651516a42a0c84ad05a1416397c5b',1,'WolfstagInteractive::ConvoCore::GameObjectReference']]],
  ['iuifoundation_18',['IUIFoundation',['../interfaceWolfstagInteractive_1_1ConvoCore_1_1IUIFoundation.html',1,'WolfstagInteractive::ConvoCore']]]
];
