var annotated_dup =
[
    [ "WolfstagInteractive", "namespaceWolfstagInteractive.html", [
      [ "ConvoCore", "namespaceWolfstagInteractive_1_1ConvoCore.html", [
        [ "Editor", "namespaceWolfstagInteractive_1_1ConvoCore_1_1Editor.html", [
          [ "ConvoCoreYamlWatcher", "classWolfstagInteractive_1_1ConvoCore_1_1Editor_1_1ConvoCoreYamlWatcher.html", "classWolfstagInteractive_1_1ConvoCore_1_1Editor_1_1ConvoCoreYamlWatcher" ]
        ] ],
        [ "BaseDialogueLineAction", "classWolfstagInteractive_1_1ConvoCore_1_1BaseDialogueLineAction.html", "classWolfstagInteractive_1_1ConvoCore_1_1BaseDialogueLineAction" ],
        [ "CharacterRepresentationBase", "classWolfstagInteractive_1_1ConvoCore_1_1CharacterRepresentationBase.html", "classWolfstagInteractive_1_1ConvoCore_1_1CharacterRepresentationBase" ],
        [ "ContainerInput", "classWolfstagInteractive_1_1ConvoCore_1_1ContainerInput.html", "classWolfstagInteractive_1_1ConvoCore_1_1ContainerInput" ],
        [ "ConversationBranchResult", "structWolfstagInteractive_1_1ConvoCore_1_1ConversationBranchResult.html", "structWolfstagInteractive_1_1ConvoCore_1_1ConversationBranchResult" ],
        [ "ConversationContainer", "classWolfstagInteractive_1_1ConvoCore_1_1ConversationContainer.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConversationContainer" ],
        [ "ConversationContainerRuntime", "classWolfstagInteractive_1_1ConvoCore_1_1ConversationContainerRuntime.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConversationContainerRuntime" ],
        [ "ConvoCore", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCore.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCore" ],
        [ "ConvoCoreAddressablesUtil", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAddressablesUtil.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAddressablesUtil" ],
        [ "ConvoCoreCharacterDisplayBase", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterDisplayBase.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterDisplayBase" ],
        [ "ConvoCoreCharacterExpression", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterExpression.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterExpression" ],
        [ "ConvoCoreCharacterProfileBaseData", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterProfileBaseData.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterProfileBaseData" ],
        [ "ConvoCoreConversationData", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreConversationData.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreConversationData" ],
        [ "ConvoCoreDialogueHistoryUI", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueHistoryUI.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueHistoryUI" ],
        [ "ConvoCoreDialogueLineActionDialogueLineActionGroup", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionDialogueLineActionGroup.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionDialogueLineActionGroup" ],
        [ "ConvoCoreDialogueLineActionEnableDisableGameObject", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionEnableDisableGameObject.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionEnableDisableGameObject" ],
        [ "ConvoCoreDialogueLineActionFadeInOutSpriteRenderer", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionFadeInOutSpriteRenderer.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionFadeInOutSpriteRenderer" ],
        [ "ConvoCoreDialogueLineActionInstantiatePrefab", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionInstantiatePrefab.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionInstantiatePrefab" ],
        [ "ConvoCoreDialogueLineActionModifyTransform", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionModifyTransform.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionModifyTransform" ],
        [ "ConvoCoreDialogueLineActionPlayAudioClip", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionPlayAudioClip.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionPlayAudioClip" ],
        [ "ConvoCoreDialogueLocalizationHandler", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLocalizationHandler.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLocalizationHandler" ],
        [ "ConvoCoreHistoryRendererProfile", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreHistoryRendererProfile.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreHistoryRendererProfile" ],
        [ "ConvoCoreHistoryRendererRegistry", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreHistoryRendererRegistry.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreHistoryRendererRegistry" ],
        [ "ConvoCoreLanguageManager", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageManager.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageManager" ],
        [ "ConvoCoreLanguageSettings", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageSettings.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageSettings" ],
        [ "ConvoCoreLanguageSettingsLoader", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageSettingsLoader.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageSettingsLoader" ],
        [ "ConvoCoreLineID", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLineID.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLineID" ],
        [ "ConvoCoreLineIDUtility", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLineIDUtility.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLineIDUtility" ],
        [ "ConvoCorePrefabPool", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCorePrefabPool.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCorePrefabPool" ],
        [ "ConvoCorePrefabRepresentationSpawner", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCorePrefabRepresentationSpawner.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCorePrefabRepresentationSpawner" ],
        [ "ConvoCoreSampleUI", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSampleUI.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSampleUI" ],
        [ "ConvoCoreSettings", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSettings.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSettings" ],
        [ "ConvoCoreUIFoundation", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreUIFoundation.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreUIFoundation" ],
        [ "ConvoCoreYamlLoader", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlLoader.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlLoader" ],
        [ "ConvoCoreYamlParser", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlParser.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlParser" ],
        [ "ConvoCoreYamlSerializer", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlSerializer.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlSerializer" ],
        [ "ConvoCoreYamlUtilities", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlUtilities.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlUtilities" ],
        [ "DefaultConversationContext", "classWolfstagInteractive_1_1ConvoCore_1_1DefaultConversationContext.html", "classWolfstagInteractive_1_1ConvoCore_1_1DefaultConversationContext" ],
        [ "DialogueHistoryEntry", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueHistoryEntry.html", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueHistoryEntry" ],
        [ "DialogueHistoryRendererContext", "structWolfstagInteractive_1_1ConvoCore_1_1DialogueHistoryRendererContext.html", "structWolfstagInteractive_1_1ConvoCore_1_1DialogueHistoryRendererContext" ],
        [ "DialogueLineDisplayOptions", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueLineDisplayOptions.html", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueLineDisplayOptions" ],
        [ "DialogueYamlConfig", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueYamlConfig.html", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueYamlConfig" ],
        [ "ExpressionIDSelectorAttribute", "classWolfstagInteractive_1_1ConvoCore_1_1ExpressionIDSelectorAttribute.html", "classWolfstagInteractive_1_1ConvoCore_1_1ExpressionIDSelectorAttribute" ],
        [ "GameObjectHelper", "classWolfstagInteractive_1_1ConvoCore_1_1GameObjectHelper.html", "classWolfstagInteractive_1_1ConvoCore_1_1GameObjectHelper" ],
        [ "GameObjectReference", "classWolfstagInteractive_1_1ConvoCore_1_1GameObjectReference.html", "classWolfstagInteractive_1_1ConvoCore_1_1GameObjectReference" ],
        [ "IConversationContext", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConversationContext.html", null ],
        [ "IConvoCoreCharacterDisplay", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreCharacterDisplay.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreCharacterDisplay" ],
        [ "IConvoCoreFadeIn", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeIn.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeIn" ],
        [ "IConvoCoreFadeOut", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeOut.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeOut" ],
        [ "IConvoCoreHistoryRenderer", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreHistoryRenderer.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreHistoryRenderer" ],
        [ "IConvoCoreLanguageSettingsLoader", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreLanguageSettingsLoader.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreLanguageSettingsLoader" ],
        [ "IConvoCoreRepresentationInitializable", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRepresentationInitializable.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRepresentationInitializable" ],
        [ "IConvoCoreRunner", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRunner.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRunner" ],
        [ "IConvoInput", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoInput.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoInput" ],
        [ "IDialogueHistoryOutput", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutput.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutput" ],
        [ "IDialogueHistoryOutputPrefab", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutputPrefab.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutputPrefab" ],
        [ "IDialogueLineEditorCustomizable", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueLineEditorCustomizable.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueLineEditorCustomizable" ],
        [ "IEditorPreviewableRepresentation", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IEditorPreviewableRepresentation.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IEditorPreviewableRepresentation" ],
        [ "IUIFoundation", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IUIFoundation.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IUIFoundation" ],
        [ "LocalizedDialogueResult", "classWolfstagInteractive_1_1ConvoCore_1_1LocalizedDialogueResult.html", "classWolfstagInteractive_1_1ConvoCore_1_1LocalizedDialogueResult" ],
        [ "PagedListAttribute", "classWolfstagInteractive_1_1ConvoCore_1_1PagedListAttribute.html", "classWolfstagInteractive_1_1ConvoCore_1_1PagedListAttribute" ],
        [ "PlainTextHistoryRenderer", "classWolfstagInteractive_1_1ConvoCore_1_1PlainTextHistoryRenderer.html", "classWolfstagInteractive_1_1ConvoCore_1_1PlainTextHistoryRenderer" ],
        [ "PrefabCharacterRepresentationData", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabCharacterRepresentationData.html", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabCharacterRepresentationData" ],
        [ "PrefabDialogueHistoryOutput", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabDialogueHistoryOutput.html", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabDialogueHistoryOutput" ],
        [ "PrefabExpressionMapping", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabExpressionMapping.html", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabExpressionMapping" ],
        [ "PrefabHistoryRenderer", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabHistoryRenderer.html", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabHistoryRenderer" ],
        [ "RepresentationExpressionOverride", "classWolfstagInteractive_1_1ConvoCore_1_1RepresentationExpressionOverride.html", "classWolfstagInteractive_1_1ConvoCore_1_1RepresentationExpressionOverride" ],
        [ "RepresentationPair", "classWolfstagInteractive_1_1ConvoCore_1_1RepresentationPair.html", "classWolfstagInteractive_1_1ConvoCore_1_1RepresentationPair" ],
        [ "RichTextHistoryRenderer", "classWolfstagInteractive_1_1ConvoCore_1_1RichTextHistoryRenderer.html", "classWolfstagInteractive_1_1ConvoCore_1_1RichTextHistoryRenderer" ],
        [ "SimplePrefabRepresentationDisplay", "classWolfstagInteractive_1_1ConvoCore_1_1SimplePrefabRepresentationDisplay.html", "classWolfstagInteractive_1_1ConvoCore_1_1SimplePrefabRepresentationDisplay" ],
        [ "SingleConversationInput", "classWolfstagInteractive_1_1ConvoCore_1_1SingleConversationInput.html", "classWolfstagInteractive_1_1ConvoCore_1_1SingleConversationInput" ],
        [ "SpriteCharacterRepresentationData", "classWolfstagInteractive_1_1ConvoCore_1_1SpriteCharacterRepresentationData.html", "classWolfstagInteractive_1_1ConvoCore_1_1SpriteCharacterRepresentationData" ],
        [ "SpriteExpressionMapping", "classWolfstagInteractive_1_1ConvoCore_1_1SpriteExpressionMapping.html", "classWolfstagInteractive_1_1ConvoCore_1_1SpriteExpressionMapping" ],
        [ "TMPDialogueHistoryOutput", "classWolfstagInteractive_1_1ConvoCore_1_1TMPDialogueHistoryOutput.html", "classWolfstagInteractive_1_1ConvoCore_1_1TMPDialogueHistoryOutput" ]
      ] ]
    ] ],
    [ "BaseExpressionAction", "classBaseExpressionAction.html", "classBaseExpressionAction" ],
    [ "ExpressionActionContext", "structExpressionActionContext.html", "structExpressionActionContext" ]
];