var ConvoCoreConversationSaveManager_8cs =
[
    [ "WolfstagInteractive.ConvoCore.SaveSystem.ConvoCoreConversationSaveManager", "classWolfstagInteractive_1_1ConvoCore_1_1SaveSystem_1_1ConvoCoreConversationSaveManager.html", "classWolfstagInteractive_1_1ConvoCore_1_1SaveSystem_1_1ConvoCoreConversationSaveManager" ]
];