var dir_716fc4c6cb98b933cc0fa884d6e5d043 =
[
    [ "ConvoCoreContainers", "dir_610fcbfc3bd96f3150ee927b0b681e14.html", "dir_610fcbfc3bd96f3150ee927b0b681e14" ],
    [ "ConvoCoreHelpers", "dir_46dfb0738a1b8b9e6b30a912d9b04ab6.html", "dir_46dfb0738a1b8b9e6b30a912d9b04ab6" ],
    [ "ConvoCoreYaml", "dir_f1ac31342a31fd6c0d822532bb9a9535.html", "dir_f1ac31342a31fd6c0d822532bb9a9535" ],
    [ "SampleActions", "dir_9b72daf09de1f33ce18b4af2f76272d3.html", "dir_9b72daf09de1f33ce18b4af2f76272d3" ],
    [ "UI", "dir_e8e5252a032b07c14d70a7941b1137c4.html", "dir_e8e5252a032b07c14d70a7941b1137c4" ],
    [ "BaseDialogueLineAction.cs", "BaseDialogueLineAction_8cs.html", "BaseDialogueLineAction_8cs" ],
    [ "BaseExpressionAction.cs", "BaseExpressionAction_8cs.html", "BaseExpressionAction_8cs" ],
    [ "CharacterRepresentationBase.cs", "CharacterRepresentationBase_8cs.html", "CharacterRepresentationBase_8cs" ],
    [ "ConvoCore.cs", "ConvoCore_8cs.html", "ConvoCore_8cs" ],
    [ "ConvoCoreAddressablesUtil.cs", "ConvoCoreAddressablesUtil_8cs.html", "ConvoCoreAddressablesUtil_8cs" ],
    [ "ConvoCoreCharacterDisplayBase.cs", "ConvoCoreCharacterDisplayBase_8cs.html", "ConvoCoreCharacterDisplayBase_8cs" ],
    [ "ConvoCoreCharacterExpression.cs", "ConvoCoreCharacterExpression_8cs.html", "ConvoCoreCharacterExpression_8cs" ],
    [ "ConvoCoreCharacterProfileBaseData.cs", "ConvoCoreCharacterProfileBaseData_8cs.html", "ConvoCoreCharacterProfileBaseData_8cs" ],
    [ "ConvoCoreConversationData.cs", "ConvoCoreConversationData_8cs.html", "ConvoCoreConversationData_8cs" ],
    [ "ConvoCoreConversationData.DialogueLineInfo.cs", "ConvoCoreConversationData_8DialogueLineInfo_8cs.html", "ConvoCoreConversationData_8DialogueLineInfo_8cs" ],
    [ "ConvoCoreDialogueLocalizationHandler.cs", "ConvoCoreDialogueLocalizationHandler_8cs.html", "ConvoCoreDialogueLocalizationHandler_8cs" ],
    [ "ConvoCoreLanguageManager.cs", "ConvoCoreLanguageManager_8cs.html", "ConvoCoreLanguageManager_8cs" ],
    [ "ConvoCoreLanguageSettings.cs", "ConvoCoreLanguageSettings_8cs.html", "ConvoCoreLanguageSettings_8cs" ],
    [ "ConvoCoreLanguageSettingsLoader.cs", "ConvoCoreLanguageSettingsLoader_8cs.html", "ConvoCoreLanguageSettingsLoader_8cs" ],
    [ "ConvoCoreSettings.cs", "ConvoCoreSettings_8cs.html", "ConvoCoreSettings_8cs" ],
    [ "DialogueLineDisplayOptions.cs", "DialogueLineDisplayOptions_8cs.html", "DialogueLineDisplayOptions_8cs" ],
    [ "EmotionIDSelectorAttribute.cs", "EmotionIDSelectorAttribute_8cs.html", "EmotionIDSelectorAttribute_8cs" ],
    [ "IConvoCoreCharacterDisplay.cs", "IConvoCoreCharacterDisplay_8cs.html", "IConvoCoreCharacterDisplay_8cs" ],
    [ "IDialogueLineEditorCustomizable.cs", "IDialogueLineEditorCustomizable_8cs.html", "IDialogueLineEditorCustomizable_8cs" ],
    [ "IEditorPreviewableRepresentation.cs", "IEditorPreviewableRepresentation_8cs.html", "IEditorPreviewableRepresentation_8cs" ],
    [ "PagedListAttribute.cs", "PagedListAttribute_8cs.html", "PagedListAttribute_8cs" ],
    [ "PrefabCharacterRepresentationData.cs", "PrefabCharacterRepresentationData_8cs.html", "PrefabCharacterRepresentationData_8cs" ],
    [ "SimplePrefabRepresentationDisplay.cs", "SimplePrefabRepresentationDisplay_8cs.html", "SimplePrefabRepresentationDisplay_8cs" ],
    [ "SpriteCharacterRepresentationData.cs", "SpriteCharacterRepresentationData_8cs.html", "SpriteCharacterRepresentationData_8cs" ]
];